<?php

namespace DBGPlatform\Database;

class Migrator
{
    public function run(): void
    {
        global $wpdb;
        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        $charset = $wpdb->get_charset_collate();
        $prefix = $wpdb->prefix . 'dbg_';
        foreach ($this->tables($prefix, $charset) as $sql) { dbDelta($sql); }
        update_option('dbg_platform_db_version', '0.8.0');
    }

    private function tables(string $prefix, string $charset): array
    {
        return [
            "CREATE TABLE {$prefix}organisations (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, uuid CHAR(36) NULL, name VARCHAR(255) NOT NULL, legal_name VARCHAR(255) NULL, type VARCHAR(64) NOT NULL, status VARCHAR(64) NOT NULL DEFAULT 'active', vat_number VARCHAR(64) NULL, siret VARCHAR(32) NULL, ape VARCHAR(32) NULL, email VARCHAR(190) NULL, phone VARCHAR(64) NULL, website VARCHAR(255) NULL, address TEXT NULL, postal_code VARCHAR(32) NULL, city VARCHAR(120) NULL, country VARCHAR(120) NULL, logo_asset_id BIGINT UNSIGNED NULL, notes TEXT NULL, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, archived_at DATETIME NULL, PRIMARY KEY (id), UNIQUE KEY uuid (uuid), KEY type (type), KEY status (status), KEY city (city), KEY created_by (created_by), KEY updated_by (updated_by)) {$charset};",
            "CREATE TABLE {$prefix}organisation_contacts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, organisation_id BIGINT UNSIGNED NOT NULL, first_name VARCHAR(120) NOT NULL, last_name VARCHAR(120) NOT NULL, job_title VARCHAR(190) NULL, email VARCHAR(190) NULL, phone VARCHAR(64) NULL, mobile VARCHAR(64) NULL, department VARCHAR(120) NULL, is_primary TINYINT(1) NOT NULL DEFAULT 0, notes TEXT NULL, status VARCHAR(64) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, archived_at DATETIME NULL, PRIMARY KEY (id), KEY organisation_id (organisation_id), KEY email (email), KEY is_primary (is_primary), KEY status (status)) {$charset};",
            "CREATE TABLE {$prefix}organisation_users (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, organisation_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, role VARCHAR(64) NOT NULL DEFAULT 'viewer', is_owner TINYINT(1) NOT NULL DEFAULT 0, status VARCHAR(64) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, archived_at DATETIME NULL, PRIMARY KEY (id), UNIQUE KEY organisation_user (organisation_id, user_id), KEY organisation_id (organisation_id), KEY user_id (user_id), KEY role (role), KEY is_owner (is_owner), KEY status (status)) {$charset};",
            "CREATE TABLE {$prefix}organisation_settings (organisation_id BIGINT UNSIGNED NOT NULL, default_language VARCHAR(16) NOT NULL DEFAULT 'fr', default_currency VARCHAR(8) NOT NULL DEFAULT 'EUR', default_project_status VARCHAR(64) NOT NULL DEFAULT 'draft', branding_enabled TINYINT(1) NOT NULL DEFAULT 1, settings_json LONGTEXT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (organisation_id)) {$charset};",
            "CREATE TABLE {$prefix}projects (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, uuid CHAR(36) NULL, organisation_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NULL, owner_user_id BIGINT UNSIGNED NULL, project_number VARCHAR(64) NULL, name VARCHAR(255) NOT NULL, type VARCHAR(64) NOT NULL DEFAULT 'custom', status VARCHAR(64) NOT NULL DEFAULT 'draft', priority VARCHAR(32) NOT NULL DEFAULT 'normal', description TEXT NULL, budget_estimate DECIMAL(12,2) NULL, currency VARCHAR(8) NOT NULL DEFAULT 'EUR', due_date DATE NULL, started_at DATETIME NULL, completed_at DATETIME NULL, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, archived_at DATETIME NULL, PRIMARY KEY (id), UNIQUE KEY uuid (uuid), KEY organisation_id (organisation_id), KEY contact_id (contact_id), KEY owner_user_id (owner_user_id), KEY project_number (project_number), KEY type (type), KEY status (status), KEY priority (priority), KEY due_date (due_date), KEY created_by (created_by), KEY updated_by (updated_by)) {$charset};",
            "CREATE TABLE {$prefix}project_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, project_id BIGINT UNSIGNED NOT NULL, actor_id BIGINT UNSIGNED NULL, event_type VARCHAR(128) NOT NULL, title VARCHAR(255) NOT NULL, payload LONGTEXT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id), KEY project_id (project_id), KEY actor_id (actor_id), KEY event_type (event_type), KEY created_at (created_at)) {$charset};",
            "CREATE TABLE {$prefix}assets (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, uuid CHAR(36) NULL, organisation_id BIGINT UNSIGNED NOT NULL, project_id BIGINT UNSIGNED NULL, parent_asset_id BIGINT UNSIGNED NULL, type VARCHAR(64) NOT NULL DEFAULT 'document', category VARCHAR(64) NOT NULL DEFAULT 'general', name VARCHAR(255) NOT NULL, description TEXT NULL, status VARCHAR(64) NOT NULL DEFAULT 'draft', approval_status VARCHAR(64) NOT NULL DEFAULT 'not_required', current_file_record_id BIGINT UNSIGNED NULL, version_number INT UNSIGNED NOT NULL DEFAULT 1, metadata_json LONGTEXT NULL, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, archived_at DATETIME NULL, PRIMARY KEY (id), UNIQUE KEY uuid (uuid), KEY organisation_id (organisation_id), KEY project_id (project_id), KEY parent_asset_id (parent_asset_id), KEY current_file_record_id (current_file_record_id), KEY type (type), KEY category (category), KEY status (status), KEY approval_status (approval_status), KEY created_by (created_by), KEY updated_by (updated_by)) {$charset};",
            "CREATE TABLE {$prefix}asset_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, asset_id BIGINT UNSIGNED NOT NULL, actor_id BIGINT UNSIGNED NULL, event_type VARCHAR(128) NOT NULL, title VARCHAR(255) NOT NULL, payload LONGTEXT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id), KEY asset_id (asset_id), KEY actor_id (actor_id), KEY event_type (event_type), KEY created_at (created_at)) {$charset};",
            "CREATE TABLE {$prefix}quotes (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, uuid CHAR(36) NULL, organisation_id BIGINT UNSIGNED NOT NULL, project_id BIGINT UNSIGNED NULL, contact_id BIGINT UNSIGNED NULL, quote_number VARCHAR(64) NOT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(64) NOT NULL DEFAULT 'draft', currency VARCHAR(8) NOT NULL DEFAULT 'EUR', subtotal_ht DECIMAL(12,2) NOT NULL DEFAULT 0, discount_total DECIMAL(12,2) NOT NULL DEFAULT 0, tax_total DECIMAL(12,2) NOT NULL DEFAULT 0, total_ht DECIMAL(12,2) NOT NULL DEFAULT 0, total_ttc DECIMAL(12,2) NOT NULL DEFAULT 0, valid_until DATE NULL, terms TEXT NULL, notes TEXT NULL, signed_at DATETIME NULL, accepted_at DATETIME NULL, rejected_at DATETIME NULL, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, archived_at DATETIME NULL, PRIMARY KEY (id), UNIQUE KEY uuid (uuid), UNIQUE KEY quote_number (quote_number), KEY organisation_id (organisation_id), KEY project_id (project_id), KEY contact_id (contact_id), KEY status (status), KEY valid_until (valid_until), KEY created_by (created_by), KEY updated_by (updated_by)) {$charset};",
            "CREATE TABLE {$prefix}quote_lines (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, quote_id BIGINT UNSIGNED NOT NULL, asset_id BIGINT UNSIGNED NULL, line_type VARCHAR(64) NOT NULL DEFAULT 'item', title VARCHAR(255) NOT NULL, description TEXT NULL, quantity DECIMAL(12,3) NOT NULL DEFAULT 1, unit VARCHAR(32) NOT NULL DEFAULT 'unit', unit_price_ht DECIMAL(12,2) NOT NULL DEFAULT 0, discount_rate DECIMAL(6,3) NOT NULL DEFAULT 0, tax_rate DECIMAL(6,3) NOT NULL DEFAULT 20, line_total_ht DECIMAL(12,2) NOT NULL DEFAULT 0, line_total_ttc DECIMAL(12,2) NOT NULL DEFAULT 0, sort_order INT UNSIGNED NOT NULL DEFAULT 0, metadata_json LONGTEXT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id), KEY quote_id (quote_id), KEY asset_id (asset_id), KEY line_type (line_type), KEY sort_order (sort_order)) {$charset};",
            "CREATE TABLE {$prefix}quote_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, quote_id BIGINT UNSIGNED NOT NULL, actor_id BIGINT UNSIGNED NULL, event_type VARCHAR(128) NOT NULL, title VARCHAR(255) NOT NULL, payload LONGTEXT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id), KEY quote_id (quote_id), KEY actor_id (actor_id), KEY event_type (event_type), KEY created_at (created_at)) {$charset};",
            "CREATE TABLE {$prefix}orders (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, uuid CHAR(36) NULL, organisation_id BIGINT UNSIGNED NOT NULL, project_id BIGINT UNSIGNED NULL, quote_id BIGINT UNSIGNED NULL, contact_id BIGINT UNSIGNED NULL, order_number VARCHAR(64) NOT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(64) NOT NULL DEFAULT 'draft', payment_status VARCHAR(64) NOT NULL DEFAULT 'unpaid', production_status VARCHAR(64) NOT NULL DEFAULT 'not_started', fulfillment_status VARCHAR(64) NOT NULL DEFAULT 'not_fulfilled', currency VARCHAR(8) NOT NULL DEFAULT 'EUR', subtotal_ht DECIMAL(12,2) NOT NULL DEFAULT 0, discount_total DECIMAL(12,2) NOT NULL DEFAULT 0, tax_total DECIMAL(12,2) NOT NULL DEFAULT 0, total_ht DECIMAL(12,2) NOT NULL DEFAULT 0, total_ttc DECIMAL(12,2) NOT NULL DEFAULT 0, due_date DATE NULL, paid_at DATETIME NULL, production_started_at DATETIME NULL, completed_at DATETIME NULL, delivered_at DATETIME NULL, notes TEXT NULL, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, archived_at DATETIME NULL, PRIMARY KEY (id), UNIQUE KEY uuid (uuid), UNIQUE KEY order_number (order_number), KEY organisation_id (organisation_id), KEY project_id (project_id), KEY quote_id (quote_id), KEY contact_id (contact_id), KEY status (status), KEY payment_status (payment_status), KEY production_status (production_status), KEY fulfillment_status (fulfillment_status), KEY due_date (due_date)) {$charset};",
            "CREATE TABLE {$prefix}order_lines (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, order_id BIGINT UNSIGNED NOT NULL, quote_line_id BIGINT UNSIGNED NULL, asset_id BIGINT UNSIGNED NULL, line_type VARCHAR(64) NOT NULL DEFAULT 'item', title VARCHAR(255) NOT NULL, description TEXT NULL, quantity DECIMAL(12,3) NOT NULL DEFAULT 1, unit VARCHAR(32) NOT NULL DEFAULT 'unit', unit_price_ht DECIMAL(12,2) NOT NULL DEFAULT 0, discount_rate DECIMAL(6,3) NOT NULL DEFAULT 0, tax_rate DECIMAL(6,3) NOT NULL DEFAULT 20, line_total_ht DECIMAL(12,2) NOT NULL DEFAULT 0, line_total_ttc DECIMAL(12,2) NOT NULL DEFAULT 0, production_status VARCHAR(64) NOT NULL DEFAULT 'not_started', sort_order INT UNSIGNED NOT NULL DEFAULT 0, metadata_json LONGTEXT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id), KEY order_id (order_id), KEY quote_line_id (quote_line_id), KEY asset_id (asset_id), KEY line_type (line_type), KEY production_status (production_status), KEY sort_order (sort_order)) {$charset};",
            "CREATE TABLE {$prefix}order_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, order_id BIGINT UNSIGNED NOT NULL, actor_id BIGINT UNSIGNED NULL, event_type VARCHAR(128) NOT NULL, title VARCHAR(255) NOT NULL, payload LONGTEXT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id), KEY order_id (order_id), KEY actor_id (actor_id), KEY event_type (event_type), KEY created_at (created_at)) {$charset};",
            "CREATE TABLE {$prefix}invoices (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, uuid CHAR(36) NULL, organisation_id BIGINT UNSIGNED NOT NULL, project_id BIGINT UNSIGNED NULL, quote_id BIGINT UNSIGNED NULL, order_id BIGINT UNSIGNED NULL, contact_id BIGINT UNSIGNED NULL, invoice_number VARCHAR(64) NOT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(64) NOT NULL DEFAULT 'draft', payment_status VARCHAR(64) NOT NULL DEFAULT 'unpaid', currency VARCHAR(8) NOT NULL DEFAULT 'EUR', subtotal_ht DECIMAL(12,2) NOT NULL DEFAULT 0, discount_total DECIMAL(12,2) NOT NULL DEFAULT 0, tax_total DECIMAL(12,2) NOT NULL DEFAULT 0, total_ht DECIMAL(12,2) NOT NULL DEFAULT 0, total_ttc DECIMAL(12,2) NOT NULL DEFAULT 0, amount_paid DECIMAL(12,2) NOT NULL DEFAULT 0, amount_due DECIMAL(12,2) NOT NULL DEFAULT 0, issued_at DATETIME NULL, due_date DATE NULL, paid_at DATETIME NULL, cancelled_at DATETIME NULL, notes TEXT NULL, terms TEXT NULL, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, archived_at DATETIME NULL, PRIMARY KEY (id), UNIQUE KEY uuid (uuid), UNIQUE KEY invoice_number (invoice_number), KEY organisation_id (organisation_id), KEY project_id (project_id), KEY quote_id (quote_id), KEY order_id (order_id), KEY contact_id (contact_id), KEY status (status), KEY payment_status (payment_status), KEY due_date (due_date)) {$charset};",
            "CREATE TABLE {$prefix}invoice_lines (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, invoice_id BIGINT UNSIGNED NOT NULL, order_line_id BIGINT UNSIGNED NULL, quote_line_id BIGINT UNSIGNED NULL, asset_id BIGINT UNSIGNED NULL, line_type VARCHAR(64) NOT NULL DEFAULT 'item', title VARCHAR(255) NOT NULL, description TEXT NULL, quantity DECIMAL(12,3) NOT NULL DEFAULT 1, unit VARCHAR(32) NOT NULL DEFAULT 'unit', unit_price_ht DECIMAL(12,2) NOT NULL DEFAULT 0, discount_rate DECIMAL(6,3) NOT NULL DEFAULT 0, tax_rate DECIMAL(6,3) NOT NULL DEFAULT 20, line_total_ht DECIMAL(12,2) NOT NULL DEFAULT 0, line_total_ttc DECIMAL(12,2) NOT NULL DEFAULT 0, sort_order INT UNSIGNED NOT NULL DEFAULT 0, metadata_json LONGTEXT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id), KEY invoice_id (invoice_id), KEY order_line_id (order_line_id), KEY quote_line_id (quote_line_id), KEY asset_id (asset_id), KEY line_type (line_type), KEY sort_order (sort_order)) {$charset};",
            "CREATE TABLE {$prefix}invoice_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, invoice_id BIGINT UNSIGNED NOT NULL, actor_id BIGINT UNSIGNED NULL, event_type VARCHAR(128) NOT NULL, title VARCHAR(255) NOT NULL, payload LONGTEXT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id), KEY invoice_id (invoice_id), KEY actor_id (actor_id), KEY event_type (event_type), KEY created_at (created_at)) {$charset};",
            "CREATE TABLE {$prefix}payments (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, uuid CHAR(36) NULL, organisation_id BIGINT UNSIGNED NOT NULL, invoice_id BIGINT UNSIGNED NULL, order_id BIGINT UNSIGNED NULL, contact_id BIGINT UNSIGNED NULL, payment_number VARCHAR(64) NOT NULL, provider VARCHAR(64) NOT NULL DEFAULT 'manual', method VARCHAR(64) NOT NULL DEFAULT 'bank_transfer', status VARCHAR(64) NOT NULL DEFAULT 'pending', currency VARCHAR(8) NOT NULL DEFAULT 'EUR', amount DECIMAL(12,2) NOT NULL DEFAULT 0, fee_amount DECIMAL(12,2) NOT NULL DEFAULT 0, net_amount DECIMAL(12,2) NOT NULL DEFAULT 0, external_reference VARCHAR(190) NULL, paid_at DATETIME NULL, received_at DATETIME NULL, reconciled_at DATETIME NULL, notes TEXT NULL, metadata_json LONGTEXT NULL, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, archived_at DATETIME NULL, PRIMARY KEY (id), UNIQUE KEY uuid (uuid), UNIQUE KEY payment_number (payment_number), KEY organisation_id (organisation_id), KEY invoice_id (invoice_id), KEY order_id (order_id), KEY contact_id (contact_id), KEY provider (provider), KEY method (method), KEY status (status), KEY paid_at (paid_at)) {$charset};",
            "CREATE TABLE {$prefix}payment_allocations (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, payment_id BIGINT UNSIGNED NOT NULL, invoice_id BIGINT UNSIGNED NOT NULL, amount DECIMAL(12,2) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, PRIMARY KEY (id), KEY payment_id (payment_id), KEY invoice_id (invoice_id)) {$charset};",
            "CREATE TABLE {$prefix}payment_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, payment_id BIGINT UNSIGNED NOT NULL, actor_id BIGINT UNSIGNED NULL, event_type VARCHAR(128) NOT NULL, title VARCHAR(255) NOT NULL, payload LONGTEXT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id), KEY payment_id (payment_id), KEY actor_id (actor_id), KEY event_type (event_type), KEY created_at (created_at)) {$charset};",
            "CREATE TABLE {$prefix}media_folders (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, organisation_id BIGINT UNSIGNED NOT NULL, project_id BIGINT UNSIGNED NULL, parent_id BIGINT UNSIGNED NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, status VARCHAR(64) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id), KEY organisation_id (organisation_id), KEY project_id (project_id), KEY parent_id (parent_id), KEY slug (slug), KEY status (status)) {$charset};",
            "CREATE TABLE {$prefix}media_tags (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, color VARCHAR(24) NULL, status VARCHAR(64) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id), UNIQUE KEY slug (slug), KEY status (status)) {$charset};",
            "CREATE TABLE {$prefix}file_tag_map (file_record_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (file_record_id, tag_id), KEY file_record_id (file_record_id), KEY tag_id (tag_id)) {$charset};",
            "CREATE TABLE {$prefix}file_metadata (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, file_record_id BIGINT UNSIGNED NOT NULL, meta_key VARCHAR(190) NOT NULL, meta_value LONGTEXT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id), UNIQUE KEY file_meta_key (file_record_id, meta_key), KEY file_record_id (file_record_id), KEY meta_key (meta_key)) {$charset};",
            "CREATE TABLE {$prefix}file_records (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, asset_id BIGINT UNSIGNED NULL, organisation_id BIGINT UNSIGNED NOT NULL, project_id BIGINT UNSIGNED NULL, folder_id BIGINT UNSIGNED NULL, original_name VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, mime_type VARCHAR(128) NOT NULL, size BIGINT UNSIGNED NOT NULL DEFAULT 0, file_hash CHAR(64) NULL, path TEXT NOT NULL, url TEXT NOT NULL, thumbnail_path TEXT NULL, thumbnail_url TEXT NULL, is_favorite TINYINT(1) NOT NULL DEFAULT 0, status VARCHAR(64) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id), KEY asset_id (asset_id), KEY organisation_id (organisation_id), KEY project_id (project_id), KEY folder_id (folder_id), KEY file_hash (file_hash), KEY is_favorite (is_favorite), KEY mime_type (mime_type), KEY status (status)) {$charset};",
            "CREATE TABLE {$prefix}file_versions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, file_record_id BIGINT UNSIGNED NOT NULL, version_number INT UNSIGNED NOT NULL DEFAULT 1, original_name VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, mime_type VARCHAR(128) NOT NULL, size BIGINT UNSIGNED NOT NULL DEFAULT 0, path TEXT NOT NULL, url TEXT NOT NULL, note TEXT NULL, created_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id), KEY file_record_id (file_record_id), KEY version_number (version_number), KEY created_by (created_by)) {$charset};",
            "CREATE TABLE {$prefix}audit_logs (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, actor_id BIGINT UNSIGNED NULL, action VARCHAR(128) NOT NULL, entity_type VARCHAR(128) NOT NULL, entity_id BIGINT UNSIGNED NULL, payload LONGTEXT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id), KEY actor_id (actor_id), KEY entity_type (entity_type), KEY entity_id (entity_id), KEY action (action), KEY created_at (created_at)) {$charset};"
        ];
    }
}
